POST http://localhost:8000/signup
Content-Type: application/json

{
    "email": "goutam123@gmail.com",
    "password": "173314Gk@",
    "name":"Goutam", 
    "role":"buyer", 
    "district":"Madhubani", 
    "aadharCard":"123456789098764"
}